version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - 3002:3000 # Next.js
      - 8000:8000 # FastAPI

  db:
    image: postgres:17
    container_name: argus-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: argusvision
    ports:
      - 5434:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
