name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # Install project dependencies for better pylint analysis
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        # Run pylint on backend Python files, using .pylintrc from backend/app directory
        # Fail if score is below 8.0/10
        cd backend/app
        pylint --fail-under=8.0 *.py
